import colorsys
from PyQt5.QtGui import QColor


THEMES = {
    "ocean": {
        "name": "Ocean",
        "seed": "#1565C0",
        "light": {
            "primary": "#1565C0",
            "on_primary": "#FFFFFF",
            "primary_container": "#D1E4FF",
            "on_primary_container": "#001D36",
            "secondary": "#535F70",
            "on_secondary": "#FFFFFF",
            "secondary_container": "#D6E3F7",
            "on_secondary_container": "#101C2B",
            "tertiary": "#6B5778",
            "on_tertiary": "#FFFFFF",
            "error": "#BA1A1A",
            "on_error": "#FFFFFF",
            "error_container": "#FFDAD6",
            "on_error_container": "#410002",
            "background": "#FDFCFF",
            "on_background": "#1A1C1E",
            "surface": "#FDFCFF",
            "on_surface": "#1A1C1E",
            "surface_variant": "#E0E2EC",
            "on_surface_variant": "#44474E",
            "outline": "#74777F",
            "outline_variant": "#C4C6D0",
            "inverse_surface": "#2F3033",
            "inverse_on_surface": "#F1F0F4",
            "inverse_primary": "#9ECAFF",
            "surface_container": "#F0F0F4",
            "surface_container_high": "#E5E6EB",
        },
        "dark": {
            "primary": "#9ECAFF",
            "on_primary": "#003258",
            "primary_container": "#00497D",
            "on_primary_container": "#D1E4FF",
            "secondary": "#BAC7DB",
            "on_secondary": "#253140",
            "secondary_container": "#3B4858",
            "on_secondary_container": "#D6E3F7",
            "tertiary": "#D6BEE4",
            "on_tertiary": "#3B2948",
            "error": "#FFB4AB",
            "on_error": "#690005",
            "error_container": "#93000A",
            "on_error_container": "#FFDAD6",
            "background": "#111318",
            "on_background": "#E2E2E6",
            "surface": "#111318",
            "on_surface": "#E2E2E6",
            "surface_variant": "#44474E",
            "on_surface_variant": "#C4C6CF",
            "outline": "#8E9099",
            "outline_variant": "#44474E",
            "inverse_surface": "#E2E2E6",
            "inverse_on_surface": "#2F3033",
            "inverse_primary": "#1565C0",
            "surface_container": "#1A1C21",
            "surface_container_high": "#25272C",
        },
    },
    "forest": {
        "name": "Forest",
        "seed": "#2E7D32",
        "light": {
            "primary": "#2E7D32",
            "on_primary": "#FFFFFF",
            "primary_container": "#C8E6C9",
            "on_primary_container": "#002106",
            "secondary": "#52634F",
            "on_secondary": "#FFFFFF",
            "secondary_container": "#D5E8D0",
            "on_secondary_container": "#101F11",
            "tertiary": "#3D6473",
            "on_tertiary": "#FFFFFF",
            "error": "#BA1A1A",
            "on_error": "#FFFFFF",
            "error_container": "#FFDAD6",
            "on_error_container": "#410002",
            "background": "#FDFDF5",
            "on_background": "#1A1C19",
            "surface": "#FDFDF5",
            "on_surface": "#1A1C19",
            "surface_variant": "#DFE4D8",
            "on_surface_variant": "#43483E",
            "outline": "#73796E",
            "outline_variant": "#C3C8BC",
            "inverse_surface": "#2F312D",
            "inverse_on_surface": "#F1F1E9",
            "inverse_primary": "#81C784",
            "surface_container": "#F0F1E8",
            "surface_container_high": "#E4E6DC",
        },
        "dark": {
            "primary": "#81C784",
            "on_primary": "#003910",
            "primary_container": "#1B5E20",
            "on_primary_container": "#C8E6C9",
            "secondary": "#B9CCB4",
            "on_secondary": "#243425",
            "secondary_container": "#3A4B39",
            "on_secondary_container": "#D5E8D0",
            "tertiary": "#94CCDC",
            "on_tertiary": "#003545",
            "error": "#FFB4AB",
            "on_error": "#690005",
            "error_container": "#93000A",
            "on_error_container": "#FFDAD6",
            "background": "#11140E",
            "on_background": "#E2E3DA",
            "surface": "#11140E",
            "on_surface": "#E2E3DA",
            "surface_variant": "#43483E",
            "on_surface_variant": "#C3C8BC",
            "outline": "#8D9387",
            "outline_variant": "#43483E",
            "inverse_surface": "#E2E3DA",
            "inverse_on_surface": "#2F312D",
            "inverse_primary": "#2E7D32",
            "surface_container": "#1A1D16",
            "surface_container_high": "#252820",
        },
    },
    "lavender": {
        "name": "Lavender",
        "seed": "#7B1FA2",
        "light": {
            "primary": "#7B1FA2",
            "on_primary": "#FFFFFF",
            "primary_container": "#F3E5F5",
            "on_primary_container": "#2E004E",
            "secondary": "#625A6C",
            "on_secondary": "#FFFFFF",
            "secondary_container": "#E8DDF2",
            "on_secondary_container": "#1E1826",
            "tertiary": "#7E5260",
            "on_tertiary": "#FFFFFF",
            "error": "#BA1A1A",
            "on_error": "#FFFFFF",
            "error_container": "#FFDAD6",
            "on_error_container": "#410002",
            "background": "#FFFBFE",
            "on_background": "#1C1B1F",
            "surface": "#FFFBFE",
            "on_surface": "#1C1B1F",
            "surface_variant": "#E7E0EC",
            "on_surface_variant": "#49454F",
            "outline": "#79747E",
            "outline_variant": "#CAC4D0",
            "inverse_surface": "#313033",
            "inverse_on_surface": "#F4EFF4",
            "inverse_primary": "#CE93D8",
            "surface_container": "#F0ECF3",
            "surface_container_high": "#E5E1E8",
        },
        "dark": {
            "primary": "#CE93D8",
            "on_primary": "#3E0055",
            "primary_container": "#6A008A",
            "on_primary_container": "#F3E5F5",
            "secondary": "#CCC1D8",
            "on_secondary": "#332D3C",
            "secondary_container": "#4A4353",
            "on_secondary_container": "#E8DDF2",
            "tertiary": "#EABDD0",
            "on_tertiary": "#462939",
            "error": "#FFB4AB",
            "on_error": "#690005",
            "error_container": "#93000A",
            "on_error_container": "#FFDAD6",
            "background": "#1C1B1F",
            "on_background": "#E6E1E5",
            "surface": "#1C1B1F",
            "on_surface": "#E6E1E5",
            "surface_variant": "#49454F",
            "on_surface_variant": "#CAC4D0",
            "outline": "#938F99",
            "outline_variant": "#49454F",
            "inverse_surface": "#E6E1E5",
            "inverse_on_surface": "#313033",
            "inverse_primary": "#7B1FA2",
            "surface_container": "#252428",
            "surface_container_high": "#302F33",
        },
    },
    "ember": {
        "name": "Ember",
        "seed": "#D84315",
        "light": {
            "primary": "#D84315",
            "on_primary": "#FFFFFF",
            "primary_container": "#FBE9E7",
            "on_primary_container": "#3E0900",
            "secondary": "#77574A",
            "on_secondary": "#FFFFFF",
            "secondary_container": "#FFDBD0",
            "on_secondary_container": "#2C150B",
            "tertiary": "#636036",
            "on_tertiary": "#FFFFFF",
            "error": "#BA1A1A",
            "on_error": "#FFFFFF",
            "error_container": "#FFDAD6",
            "on_error_container": "#410002",
            "background": "#FFFCF9",
            "on_background": "#201A17",
            "surface": "#FFFCF9",
            "on_surface": "#201A17",
            "surface_variant": "#F5DED6",
            "on_surface_variant": "#53433C",
            "outline": "#85736B",
            "outline_variant": "#D8C2B9",
            "inverse_surface": "#362F2B",
            "inverse_on_surface": "#FBEEE9",
            "inverse_primary": "#FFB4A0",
            "surface_container": "#F5EFEA",
            "surface_container_high": "#EBE3DD",
        },
        "dark": {
            "primary": "#FFB4A0",
            "on_primary": "#561E00",
            "primary_container": "#A13100",
            "on_primary_container": "#FFDBD0",
            "secondary": "#E7BEAD",
            "on_secondary": "#442A1D",
            "secondary_container": "#5E3F32",
            "on_secondary_container": "#FFDBD0",
            "tertiary": "#C8C48E",
            "on_tertiary": "#32301A",
            "error": "#FFB4AB",
            "on_error": "#690005",
            "error_container": "#93000A",
            "on_error_container": "#FFDAD6",
            "background": "#201A17",
            "on_background": "#EDE0DB",
            "surface": "#201A17",
            "on_surface": "#EDE0DB",
            "surface_variant": "#53433C",
            "on_surface_variant": "#D8C2B9",
            "outline": "#A08D84",
            "outline_variant": "#53433C",
            "inverse_surface": "#EDE0DB",
            "inverse_on_surface": "#362F2B",
            "inverse_primary": "#D84315",
            "surface_container": "#29221E",
            "surface_container_high": "#352C27",
        },
    },
}

THEME_NAMES = list(THEMES.keys())
DEFAULT_THEME = "ocean"


class PaletteSet:
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def __getattr__(self, name):
        if name.endswith("_rgb"):
            base = name[:-4]
            if hasattr(self, base):
                c = QColor(getattr(self, base))
                return (c.red(), c.green(), c.blue())
        raise AttributeError(f"{name}")

    def to_dict(self):
        return {k: v for k, v in self.__dict__.items() if not k.startswith("_")}


def get_palette(theme_id, dark=False):
    if theme_id not in THEMES:
        theme_id = DEFAULT_THEME
    mode = "dark" if dark else "light"
    colors = THEMES[theme_id][mode]
    return PaletteSet(**colors)
